FC-1100  Permissions System
Templum/developers-community pull request #1
Opened 2022-02-11 07:31 UTC by eplazaso

2022-02-11 08:20 UTC, Templum requested changes

2022-02-11 08:20 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/permission-system.md
> +* FaaS-Invocation - only allowed to invoke lambdas externally. This permission is granted to a user dedicated to external invocations. When an external system needs to invoke a Functions `lambda`, th
Don't need to go into greater detail. People will learn what they need, under external invocations.

2022-02-11 08:21 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/permission-system.md
> +    <td style="text-align: center; vertical-align: middle;" >🔒</td>
Maybe we need to add a s short Legend under the tables

2022-02-11 10:56 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/permission-system.md
> +* FaaS-Invocation -provides basic read access on all functions and permission to invoke them. The Agent profile has this permission enabled by default.
```suggestion
* FaaS-Invocation - provides basic read access on all functions and permission to invoke them. The Agent profile has this permission enabled by default.
```

2022-02-11 11:12 UTC, Templum requested changes

2022-02-11 11:12 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/permission-system.md
> +* Be aware that user roles like Agent won't have the option to get FaaS-Developer and FaaS-Admin permission, you would need to use a different user with the proper role.
```suggestion
* Please be aware that roles like Agent don't have the option to get FaaS Developer/Admin permission. You will need to use a different role in that case.
```

2022-02-11 11:12 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/permission-system.md
> +* CLI users are following the same rules. If you create a user to be used in a CI development it requires the same permissions.
Maybe you want to link `CLI` directly to the CLI Page

```suggestion
* The CLI leverages the same permissions, therefore you need to make sure that the user used has at least the FaaS-Developer permission.
```

2022-02-11 11:12 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/permission-system.md
> +* Use only the minimum permission required. E.g, for external invocation use only a user with FaaS-Invocation permission.
```suggestion
* We suggest obeying the security principle of least privilege and therefore only selecting the minimal set of permissions. E.g. If the user will be only using function (invoking). Then the FaaS-Invocation is only required.
```

2022-02-11 11:17 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/permission-system.md
> +* Be aware that user roles like Agent won't have the option to get FaaS-Developer and FaaS-Admin permission, you would need to use a different user with the proper role.
actually is should be a profile Maybe the last sentence could be: _You will need to use another profile with a different role in that case_

2022-02-12 11:44 UTC, Templum approved these changes

2022-02-14 07:56 UTC, merged