:FC-899: :sparkles: creation of multiple lambda per events for Invocations by Skill
Templum/developers-community pull request #12
Opened 2022-03-22 10:26 UTC by agalagade

2022-03-22 11:02 UTC, Templum requested changes

2022-03-22 11:02 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +<img src="img/functions/faas-select-skill-2.png" alt="Functions select multiple skill" style="width:100%;"/>
Naming does not comply

2022-03-22 14:28 UTC, agalagade commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +<div class="important">Changing the skills of a lambda does not require a redeployment. The change is reflected within 5 minutes after saving.</div>
updated

2022-03-22 14:28 UTC, agalagade commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +<img src="img/functions/faas-select-skill-2.png" alt="Functions select multiple skill" style="width:100%;"/>
updated

2022-03-22 14:29 UTC, agalagade commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +Please note that lambda skills can only be assigned to controller bot events, for a overview of all the supported lambda skill events head over to our [Event Sources](liveperson-functions-event-sourc
updated

2022-03-22 14:29 UTC, agalagade commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +To specify to which skill the lambda should react, simply select the skills during the creation/editing process of your lambda. By default, the lambda will react to all skills. If the lambda should o
updated

2022-03-22 14:29 UTC, agalagade commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +Please note that lambda skills can only be assigned to controller bot events, for a overview of all the supported lambda skill events head over to our [Event Sources](liveperson-functions-event-sourc
resolved

2022-03-22 15:22 UTC, Templum requested changes

2022-03-22 15:22 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +### Function Skills
No heading is needed here, it destroys the flow.

2022-03-22 15:22 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +Please note that you can only assign function skills to controller bot events; for an overview of all the supported functions skill events, head over to our [Event Sources](liveperson-functions-event
Covered in the introduction paragraph. It makes no sense to explain to people how to achieve and then provide them with limits. 

```suggestion
```

2022-03-22 15:22 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +Select the skills during your function's creation/editing process to specify which skill the function should react to; By default, the function will respond to all skills. If the function should only
```suggestion
Skills can be selected via the drop-down menu, and it is populated using the skills available in the conversational cloud. By default, the function will respond to all skills. Please be aware that the maximum number of skills is **50**.

<img src="img/functions/faas_select_skill_2.png" alt="Functions select multiple skill" style="width:100%;"/>
```

2022-03-22 15:22 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +Select the skills during your function's creation/editing process to specify which skill the function should react to; By default, the function will respond to all skills. If the function should only
You might also add a short sentence explaining how the drop-down looks/behaves for other events.

2022-03-22 15:22 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +Select the skills during your function's creation/editing process to specify which skill the function should react to; By default, the function will respond to all skills. If the function should only
Further, this is **only** about the creation process, please explain the updating in the other section. If needed you can add a short section, where you also mention that updates may take up to 5 minutes and are not requiring a redeployment.

2022-03-22 15:22 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +Select the skills during your function's creation/editing process to specify which skill the function should react to; By default, the function will respond to all skills. If the function should only
But updating is nothing that should be discussed here.

2022-03-22 15:22 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +You can create more than one function of the same event if you set different skills for each function. If you do not assign a skill to the function, you can only have one function of the given event.
```suggestion
You can create more than one function of the same event if you set different skills for each function. Generally, as long as they are not overlapping, you can create multiple functions for the same event. The following Scenario should highlight the implications:
```

2022-03-22 15:22 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +✅ Event A, Skill 1,2 + Event A, Skill 3,4
```suggestion
✅  Function 1 for Event A [Skill 1,2] + Function 2 for Event A [Skill 3,4]
```

2022-03-22 15:22 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +✅ Event A, Skill 1,2 + Event A, Skill 3,4 + Event B, Default-skill
Please follow the above naming to make it more clear, as people might not get that different functions are defined between the "+"

2022-03-22 15:22 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +Changing the skills of a function does not require a redeployment. The change is reflected within 5 minutes after saving.
```suggestion
The above example, "Default-skill", refers to not selecting any skill, the default behaviour.
```

2022-03-22 15:22 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +Changing the skills of a function does not require a redeployment. The change is reflected within 5 minutes after saving.
The existing content is related to the update process, not the creation process.

2022-03-22 16:44 UTC, Templum requested changes

2022-03-22 16:44 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +
```suggestion
```

2022-03-22 16:44 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +<img src="img/functions/faas_select_skill.png" alt="Functions select multiple skill" style="width:100%;"/>
The image should be above your edge case explanation. As it is not relevant to the picture.

further the image name should start with functions_*****.png like every other file

2022-03-22 16:44 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +
This should be actually right before or after the explanation on how to set

2022-03-23 08:31 UTC, agalagade commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +<img src="img/functions/faas_select_skill_edit.png" alt="Functions select multiple skill" style="width:100%;"/>
I am looking at the file name and they are starting the same way mine are functions_**.png for example. functions_ui_debugger_sidebar.png, functions_ui_debugger_output.png

2022-03-23 08:35 UTC, agalagade commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +<img src="img/functions/faas_select_skill_edit.png" alt="Functions select multiple skill" style="width:100%;"/>
updated

2022-03-23 08:35 UTC, agalagade commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +The above example, "Default-skill", refers to not selecting any skill, the default behaviour.
moved

2022-03-23 08:35 UTC, agalagade commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +
updated

2022-03-23 08:35 UTC, agalagade commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +<img src="img/functions/faas_select_skill.png" alt="Functions select multiple skill" style="width:100%;"/>
updated

2022-03-23 08:53 UTC, Templum approved these changes
LGTM

2022-03-23 08:55 UTC, merged