FC-1157 Provisioning
Templum/developers-community pull request #3
Opened 2022-02-14 07:45 UTC by eplazaso

2022-02-14 08:03 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +In order to easily integrate LivePerson Functions, we will allow Conversational Cloud Admins to provision your account when entering LivePerson Functions. Provisioning will be triggered after you agr
```suggestion
To be able to leverage the full functionality of the LivePerson Functions platform we require to perform some provisioning tasks. This process needs to be performed by a Conversational Cloud Admin and it happens during the initial agreement to the terms of use. Further additional we may perform partial provisioning in the future if new features require them. This process will happen in the background during login to the UI.

<img src="img/faas-terms-of-use.png" alt="FaaS Terms of Use" style="width:70%;"/>

Following provisioning tasks will be performed:
```

2022-02-14 08:04 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +In order to easily integrate LivePerson Functions, we will allow Conversational Cloud Admins to provision your account when entering LivePerson Functions. Provisioning will be triggered after you agr
Maybe width can be also set to 100%, check how it looks with 70%

2022-02-14 08:04 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +<img src="img/faas-terms-of-use.png" alt="FaaS Terms of Use" style="width:100%;"/>
```suggestion
```

2022-02-14 08:05 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +Once agreed, we will automatically set up your account to easily integrate with the rest of the LivePerson ecosystem including:
```suggestion
```

2022-02-14 08:07 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +#### Lp-faas-orchestrator-app-key privileges
```suggestion
#### lp-faas-orchestrator-app-key privileges
```

2022-02-14 08:07 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +* **Lp-faas-orchestrator-app-key**: Required for [Toolbelt](function-as-a-service-foundations-features.html) OrchestratorFN client.
```suggestion
* **lp-faas-orchestrator-app-key**: Required for [Toolbelt](function-as-a-service-foundations-features.html) OrchestratorFN client.
```

2022-02-14 08:08 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +* **Lp-faas-orchestrator-app-key**: Required for [Toolbelt](function-as-a-service-foundations-features.html) OrchestratorFN client.
```suggestion
* **Lp-faas-orchestrator-app-key**: This secret is required and used for the Orchestrator Feature, which is available in the Toolbelt.
```

2022-02-14 08:08 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +* **Lp-faas-orchestrator-app-key**: Required for [Toolbelt](function-as-a-service-foundations-features.html) OrchestratorFN client.
Link should be on the Orchestrator Feature

2022-02-14 08:09 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +* **lp-faas-default-app-key**: Required for internal LivePerson API calls.
```suggestion
* **lp-faas-default-app-key**: This secret is required and used by the LP Client to access LivePerson Apis, which is available in the Toolbelt.
```

2022-02-14 08:10 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +* **lp-faas-default-app-key**: Required for internal LivePerson API calls.
The link should go to LP CLient.

2022-02-14 08:11 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +    <td style="text-align: center; vertical-align: middle;" >true</td>
This is nothing for the users of the platform, it is internal knowledge.... Remove it and replace it with easier to understand API's names

2022-02-14 08:12 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +  </tbody>
Same as the above

2022-02-14 08:12 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +The [Toolbelt](function-as-a-service-foundations-features.html) clients use the bellow domains to call internal LivePerson APIs. Those APIs domains are whitelisted during provisioning and are accessi
```suggestion
The [Toolbelt](function-as-a-service-foundations-features.html) clients use the below domains to call internal LivePerson APIs. Those APIs domains are whitelisted during provisioning and are accessible from the functions.
```

2022-02-14 08:20 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +<img src="img/faas-terms-of-use.png" alt="FaaS Terms of Use" style="width:100%;"/>
so we should remove the image? i thin it looks better with that screenshot

2022-02-15 13:42 UTC, chrbrt requested changes

2022-02-15 13:42 UTC, chrbrt commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +Functions interaction with other LivePerson APIs need to get authenticated therefore key/secrets are required. During provisioning, the following secrets are added to your account by default.
```suggestion
Interaction between Functions and other LivePerson APIs needs to get authenticated. Therefore, special key/secret pairs are added to your account during provisioning. These secrets are as follows:
```

2022-02-15 13:42 UTC, chrbrt commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +<div class="notice">In order to facilitate functions development, Toolbelt clients for internal APIs make use of those secrets, in this way the functions developers don't need to implement any authen
```suggestion
<div class="notice">In order to ease functions development, Toolbelt clients for internal APIs make use of those secrets, in this way the functions developers don't need to implement any authentication method for those APIs.</div>
```

2022-02-15 13:42 UTC, chrbrt commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +The [Toolbelt](function-as-a-service-foundations-features.html) clients use the below domains to call internal LivePerson APIs. Those APIs domains are whitelisted during provisioning and are accessib
```suggestion
The [Toolbelt](function-as-a-service-foundations-features.html) clients use the domains below to call internal LivePerson APIs. These API domains are whitelisted during provisioning and are accessible from your functions.
```

2022-02-15 13:42 UTC, chrbrt commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +    <td style="text-align: center; vertical-align: middle;" >Build custom visitor experiences for messaging. Build a visitor chat experience outside of the web browser environment. Create a session,
same as asyncMessaging (?) not sure if necessary or whats the difference here.

2022-02-15 13:42 UTC, chrbrt commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +    <td style="text-align: center; vertical-align: middle;" >Build custom visitor experiences for messaging. Build a visitor chat experience outside of the web browser environment. Create a session,
```suggestion
    <td style="text-align: center; vertical-align: middle;" >Build a custom visitor experiences for messaging or a visitor chat experience outside of the web browser environment. Create a session, read agent lines, send your own lines, etc.</td>
```

2022-02-15 13:42 UTC, chrbrt commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +    <td style="text-align: center; vertical-align: middle;" >Work and register to LivePerson's push notification service</td>
```suggestion
    <td style="text-align: center; vertical-align: middle;" >Work and register to LivePerson's push notification service.</td>
```

2022-02-15 13:42 UTC, chrbrt commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +    <td style="text-align: center; vertical-align: middle;" >Keep track of and make requests for data deletion to comply with GDPR</td>
```suggestion
    <td style="text-align: center; vertical-align: middle;" >Keep track of and make requests for data deletion to comply with GDPR.</td>
```

2022-02-15 13:42 UTC, chrbrt commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +    <td style="text-align: center; vertical-align: middle;" >Retrieve one consumer's messaging data for the last 13 months.</td>
```suggestion
    <td style="text-align: center; vertical-align: middle;" >Retrieve a single consumer's messaging data for the last 13 months.</td>
```

2022-02-15 13:48 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +    <td style="text-align: center; vertical-align: middle;" >Build custom visitor experiences for messaging. Build a visitor chat experience outside of the web browser environment. Create a session,
I was haven't really found the difference, I just found that usually both domains are used for the same APIs but it can change for some customers, but don't know more... https://confluence.liveperson.com/display/SOCIAL/Development+on+UMS

2022-02-15 14:33 UTC, Templum requested changes

2022-02-15 14:33 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +* **lp-faas-default-app-key**: This secret is required and used by the LP Client to access LivePerson Apis, which is available in the Toolbelt.
Missing link to toolbelt

2022-02-16 08:38 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +* **Lp-faas-orchestrator-app-key**: Required for [Toolbelt](function-as-a-service-foundations-features.html) OrchestratorFN client.
But is also a defautlt key, i think it should be in both

2022-02-16 12:09 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +* **Lp-faas-orchestrator-app-key**: Required for [Toolbelt](function-as-a-service-foundations-features.html) OrchestratorFN client.
But we have no link at all here

2022-02-16 12:10 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +* **Lp-faas-orchestrator-app-key**: Required for [Toolbelt](function-as-a-service-foundations-features.html) OrchestratorFN client.
Please add a link from `Orchestrator Feature` to the Toolbelt (later we will than need to adjust it to the correct subpage)

2022-03-04 08:52 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +<img src="img/faas-terms-of-use.png" alt="Functions: Terms of Use" style="width:100%;"/>
@eplazaso pushes are changed. You can now rebase it on master and make the change (all images are located inside functions folder)

2022-03-04 14:24 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +<img src="img/faas-terms-of-use.png" alt="Functions: Terms of Use" style="width:100%;"/>
Added proper image in the right folder

2022-03-04 14:28 UTC, chrbrt commented on pages/Documents/DeveloperTools/LivePersonFunctions/provisioning.md
> +    <td style="text-align: center; vertical-align: middle;" >Build custom visitor experiences for messaging. Build a visitor chat experience outside of the web browser environment. Create a session,
👍

2022-03-07 09:50 UTC, merged