:memo: FC-1158 New documentation for getting started
Templum/developers-community pull request #4
Opened 2022-02-15 14:06 UTC by Templum

2022-02-15 15:15 UTC, chrbrt requested changes

2022-02-15 15:50 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/configure.md
> +We offer a secret store based on Vault that is available to functions at runtime. And allow access to a pool of account specific secrets. There are also some default secrets, that are created as part
Actually, you have a legit point here, let me remove it. Idea was to give them a sense of security, given Vault is a battle-tested solution for secret storage.

2022-03-02 09:58 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/liveperson-functions-cli.md
> +To get the correct domain for your account use the [Domain Retrieval tool](https://developers.liveperson.com/agent-domain-domain-api.html) select the value for agent-vep from the list. Fill out all t
We should avoid using full domains when we reference to developer stuff (as we don't use it for our links)

2022-03-04 07:52 UTC, chrbrt commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/liveperson-functions-cli.md
> +To get the correct domain for your account use the [Domain Retrieval tool](https://developers.liveperson.com/agent-domain-domain-api.html) select the value for agent-vep from the list. Fill out all t
done

2022-03-04 07:53 UTC, chrbrt commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-cli.md
> +The CLI is optimized for use with macOS and Linux. If you want to use the CLI from a Windows machine we recommend using the linux subsystem.
done

2022-03-04 08:43 UTC, chrbrt approved these changes

2022-03-04 08:43 UTC, merged