Fc 1146 event sources
Templum/developers-community pull request #7
Opened 2022-03-03 15:23 UTC by eplazaso

2022-03-03 15:36 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +With Functions for messaging you are able to invoke `lambdas` from standard messaging events thanks to our integration with Automatic Messages. Along with the invocation, the function is sent a paylo
```suggestion
Thanks to our integration with Automatic Messages we are able to have functions being triggered based on selected events. During the invocation, a payload is sent to a function containing metadata related to the specific conversation and based on the selected event. This payload can then be used in the function for further processing and referencing.
```

2022-03-03 15:37 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +<div class="important">If an specific system message is disabled, the associated function will be invoked regardless of the state of the enabled flag.</div>
In situation where you want to warn the user, please prefer notice block over this div approach
```suggestion
<div class="important">If an specific system message is disabled, the associated function will be invoked regardless of the state of the enabled flag.</div>
```

2022-03-03 15:39 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +You can select one of the available [templates](liveperson-functions-event-sources-overview.html#templates) for the chosen event. Currently, only one function per template type can be created for tho
```suggestion
You can select one of the available [templates](liveperson-functions-event-sources-overview.html#templates) for the chosen event. Currently, only one function per template type can be created for those conversational events. If there are multiple types of functionality needed that stem from the same event invocation, these should be coded into the same `lambda`.
```

Here we could make advertisement for our orchestrator functions

2022-03-03 15:40 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +Adjust the coding from the template according to your needs by modifying the function. The function can return a series of commands back to the invoker.
Linkt to the relevant Deep Dive CLI/UI section here

2022-03-03 15:40 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +
Linkt to the relevant Deep Dive CLI/UI section here

2022-03-03 15:40 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +
Not the first function guide !

2022-03-03 15:44 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +        }</code>. To set the message empty just pass <code>[]</code> as text.
Please ```json/js instead of <code> and `` over <code> when inlined....

Overall **avoid** HTML inside markdown

2022-03-04 07:59 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +    2. Transfer Conversation to a different Agent.
forgot

2022-03-04 08:05 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +<div class="important">If an specific system message is disabled, the associated function will be invoked regardless of the state of the enabled flag.</div>
you mean with this: {: .important}?

2022-03-04 08:35 UTC, Templum requested changes

2022-03-04 08:35 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +Functions for messaging listens for messaging events asynchronously. As a consequence this can cause race conditions with other parts of the platform. Therefore, it is considered best practice to use
```suggestion
Functions for messaging listens for messaging events asynchronously. As a consequence, this can cause race conditions with other parts of the conversation cloud. Therefore, it is considered best practice to use bots instead of Functions for implementing routing logic. Functions are a good option to enrich data with third-party systems like CRMs or to save data in the [Conversation Context Service](maven-context-warehouse-overview.html) in order to make it usable by another system like the Conversation Orchestrator. Routing via Functions makes sense whenever a conversation is in a stagnant state (i.e. not in process of being routed), e.g. a conversation is idle or a message line has been sent in off-hours. Otherwise, the asynchronous nature of its events might interfere with the proper flow of a "dynamic" conversation.
```

2022-03-04 08:35 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +<div class="important">if the authenticated consumer's previous conversation was auto-closed, and the new one opened within 48 hours of that, the new conversation event won't be triggered.</div>
notice

2022-03-04 08:35 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +#### Controller Bot will Retry on failed invocation
```suggestion
#### Automatic Messages Error Handling
```

2022-03-04 08:35 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +If your function invocation takes too long or you have coding errors, the Controller Bot will retry up to 3 times, this will increase the number of invocations when your function does not perform wel
Never use controller bot...

2022-03-04 08:35 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +<div class="important">Controller Bot will retry up to 3 times when an invocation fails.</div>
Avoid div, just make it **big**

2022-03-04 08:35 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +Since multiple conversational events are mapped to the same Functions event, you can differentiate the conversational event by the `cbotEventType` property in the invocation payload and adapt your fo
This is something you mention in the chapter where you speak about the mapping

2022-03-04 08:35 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +#### Any automatic message is disabled
This should not be a subtitel. It is something you can fit into the main text. Cutting down on the relevant information, that functions will be invoked even when auto message(s) are disabled. In order to completely avoid firing of functions you can either a or b

2022-03-04 08:35 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/chat-post-survey.md
> +Chat Post Survey integrates LivePerson Functions with LiveEngage Chat. This integration will use Functions to re-create one of our Legacy features, the ability to conditionally send out email transcr
Is chat or messaging the legacy

2022-03-04 08:35 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/chat-post-survey.md
> +There is not further requirements than FaaS feature enabled. Remember that this integration is available only with LiveEngage Chat.
```suggestion
There is no further requirements than that  FaaS was [provisioned](link to provisioning). Remember that this integration is available only with LiveEngage Chat.
```

2022-03-04 08:35 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/chat-post-survey.md
> +There is not further requirements than FaaS feature enabled. Remember that this integration is available only with LiveEngage Chat.
Doube-check if this is still the real name. Given we have conversation cloud now and not Live engange

2022-03-04 08:35 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/chat-post-survey.md
> +Just like any other function, this function must be deployed before it can be used. [Please see this document](liveperson-functions-getting-started-your-first-function.html#deploy) for more informati
Link to deep dive

2022-03-04 08:35 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/chat-post-survey.md
> +Create a new `lambda` from **Chat Post Survey E-mail Transcript** event. The default template for this event will be selected for the function.
Here you can link to deep dive

2022-03-04 08:35 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/chat-post-survey.md
> +Based on the payload sent from the Conversational Cloud server described bellow, this could be an example `lambda` that processes the data within LivePerson Functions and returns a list of email addr
There is no payload shown. So don't refer to it

2022-03-04 08:35 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/chat-post-survey.md
> +};
This is not even a legit lambda in terms of our current function. Please re-write it

2022-03-04 08:35 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/chat-post-survey.md
> +};
Also module.exports is not encouraged by us. So avoid referring to it

2022-03-04 08:35 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/chat-post-survey.md
> +Based on the payload sent from the Conversational Cloud server described bellow, this could be an example `lambda` that processes the data within LivePerson Functions and returns a list of email addr
So after seeing it. You should restructure the whole paragraph. First show the Payload (without the need to have a subheader).

Then you introduce your example function with the text (while changing the wording) and finally you show the code.

2022-03-04 08:35 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/conversation-builder.md
> +Users who are tasked with creating bots in Conversation Builder can easily integrate function calls within their dialog flows. Adding this kind of [integration interaction](conversation-builder-integ
```suggestion
Users who are tasked with creating bots in Conversation Builder can easily integrate functions within their dialog flows. Adding this kind of [interaction](conversation-builder-integrations-liveperson-functions-integrations.html) to a dialog in a bot works just like adding any other type of integration interaction.
```

2022-03-04 08:35 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/conversation-builder.md
> +As part of the invocation, the bot can pass a payload into the function. This payload is specific to the triggered bot interaction. This means that, depending on the interaction, the function will ha
```suggestion
As part of the invocation, the bot can pass event meta-data into the function. This event payload is specific to the triggered bot interaction. This means that, depending on the interaction, the function will have different data available as an input.
```

2022-03-04 08:35 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/conversation-builder.md
> +Just like any other function, this function must be deployed before it can be used. [Please see this document](liveperson-functions-getting-started-your-first-function.html#deploy) for more informati
Deep Dive

2022-03-04 08:35 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/conversational-commands.md
> +With **Conversational Commands**, agents are able to invoke `lambdas` from the Agent Workspace by typing `/` into the messaging input in the connections panel. This empowers agents to use a bank of p
```suggestion
With Conversational Commands, agents are able to invoke `functions` from the Agent Workspace by typing `/` into the messaging input in the connections panel. This empowers agents to use a bank of preconfigured, account-specific commands, to enrich the conversation with integrated functions that will help them interact efficiently with the consumer.
```

2022-03-04 08:35 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/conversational-commands.md
> +With **Conversational Commands**, agents are able to invoke `lambdas` from the Agent Workspace by typing `/` into the messaging input in the connections panel. This empowers agents to use a bank of p
Would be careful with the wording here. It sounds almost like when you type `/` there will be a set of commands from the get-go. Which is not the case as far as I understood

2022-03-04 08:35 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/third-party-bots.md
> +Please follow the Third Party Bots [Getting Started guide](third-party-bots-getting-started.html) first to complete pre-requisite steps.
No need to have that as important and put it about the above paragraph

2022-03-04 08:37 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +<div class="important">If an specific system message is disabled, the associated function will be invoked regardless of the state of the enabled flag.</div>
{: .notice}

2022-03-04 10:37 UTC, eplazaso commented on _data/documentsupdated.yaml
> +            - subpagename: Post Conversation Survey
Post Conversation Survey  is Messaging the survey bot,  and Chat Post survey is Denver

2022-03-04 10:38 UTC, eplazaso commented on _data/documentsupdated.yaml
> +            - subpagename: Post Conversation Survey
yes is that name :https://developers.liveperson.com/conversation-builder-bots-post-conversation-survey-bots.html

2022-03-04 10:39 UTC, eplazaso commented on _data/documentsupdated.yaml
> +            - subpagename: Post Conversation Survey
this is actually the one we had for sure: https://developers.liveperson.com/messaging-window-api-tutorials-legacy-post-conversation-survey-pcs.html

2022-03-04 12:37 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +    2. Transfer Conversation to a different Agent.
done

2022-03-04 13:35 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +Adjust the coding from the template according to your needs by modifying the function. The function can return a series of commands back to the invoker.
Done check is you like

2022-03-04 13:36 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +
done

2022-03-04 13:37 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +Since multiple conversational events are mapped to the same Functions event, you can differentiate the conversational event by the `cbotEventType` property in the invocation payload and adapt your fo
removed

2022-03-04 13:38 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +#### Any automatic message is disabled
I added it at the top in the warning when I mention this the first time,

2022-03-04 13:39 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/chat-post-survey.md
> +Chat Post Survey integrates LivePerson Functions with LiveEngage Chat. This integration will use Functions to re-create one of our Legacy features, the ability to conditionally send out email transcr
Is Chat

2022-03-04 15:35 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/chat-post-survey.md
> +};
fixed

2022-03-04 15:41 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/conversational-commands.md
> +With **Conversational Commands**, agents are able to invoke `lambdas` from the Agent Workspace by typing `/` into the messaging input in the connections panel. This empowers agents to use a bank of p
I think in the image is self explained

2022-03-07 07:09 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/conversation-builder.md
> +Just like any other function, this function must be deployed before it can be used. [Please see this document](liveperson-functions-getting-started-your-first-function.html#deploy) for more informati
done , check if you like

2022-03-07 07:12 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/conversational-commands.md
> +With **Conversational Commands**, agents are able to invoke `lambdas` from the Agent Workspace by typing `/` into the messaging input in the connections panel. This empowers agents to use a bank of p
<img width="962" alt="image" src="https://user-images.githubusercontent.com/44361656/156984796-dbe66043-8c93-4ae4-a77d-1de37813f611.png">

2022-03-07 07:13 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/conversational-commands.md
> +With **Conversational Commands**, agents are able to invoke `lambdas` from the Agent Workspace by typing `/` into the messaging input in the connections panel. This empowers agents to use a bank of p
it is called "commands"

2022-03-07 09:43 UTC, Templum requested changes

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +If an specific system message is disabled, the associated function will be invoked regardless of the state of the enabled flag. In order to completely avoid firing of functions you can either undeplo
We need to be careful, ignoring won't stop the firing. So it would be still counted as an invocation, ignoring a event is optional but would still trigger an invocation

```suggestion
If a specific system message is disabled, the associated function will be invoked regardless of the state of the enabled flag. In order to completely avoid firing of functions, you have to undeploy your function. You may choose to ignore a specific event by leveraging the `cbotEventType` property, that is included in the invocation payload. However, the ignored invocations here would still count towards your usage limits.
```

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +You have the option to send commands back to the trigger. You have the option to send one command or multiple commands at a time, by simply adding them to an array. Using callback commands is **not**
```suggestion
You have the option to send commands back to the trigger. Where you can choose to send one command or multiple commands at a time, by simply adding them to an array. Using callback commands is **not** mandatory. If you don't want to take any actions, simply return an empty array `[]` this will result in no operation.
```

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +If no message is set in the result of the function (which it returns to the trigger, for example: `callback();` ), the default automatic message for the account will be triggered.
This should go before all the coding samples.

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +If no message is set in the result of the function (which it returns to the trigger, for example: `callback();` ), the default automatic message for the account will be triggered.
Especially since it touches on our suggestion to provide [] for NO-OP

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +To set the message empty just pass `[]` as text.
Can't they simply set empty string aka '' ? Honesty that makes much more sense than [], which just stringifies into an empty string ....

```suggestion
To set the message empty just pass `[]` as text.
```

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +To set the message empty just pass `[]` as text.
And if thats the case, we don't need to tell them. People should have that level of understanding anyways

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +Functions for messaging listens for messaging events asynchronously. As a consequence, this can cause race conditions with other parts of the conversation cloud. Therefore, it is considered best prac
```suggestion
Functions for messaging listens for messaging events asynchronously. As a consequence, this can cause race conditions with other parts of the conversation cloud. Therefore, it is considered best practice to use bots instead of Functions for implementing routing logic. Routing via Functions makes sense whenever a conversation is in a stagnant state (i.e. not in process of being routed), e.g. a conversation is idle or a message line has been sent in off-hours. Functions are a good option to enrich data with third-party systems like CRMs or to save data in the [Conversation Context Service](maven-context-warehouse-overview.html) in order to make it usable by another system like the Conversation Orchestrator.
```

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> + <tr><td>general</td><td>cbotEventType</td><td>&nbsp;</td><td>ID of the system message</td><td>STRING</td><td>CONSUMER_OPEN_NEW_CONVERSATION_FIRST_TIME_OFF_HOURS</td></tr>
```suggestion
 <tr><td>general</td><td>cbotEventType</td><td>&nbsp;</td><td>Original conversation event type</td><td>STRING</td><td>CONSUMER_OPEN_NEW_CONVERSATION_FIRST_TIME_OFF_HOURS</td></tr>
```

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/chat-post-survey.md
> +There is not further requirements than FaaS feature enabled. Remember that this integration is available only with LiveEngage Chat.
Still relevant

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/chat-post-survey.md
> +* Functions platform won't send out any email. The chat server will take care of sending out emails.
```suggestion
* Functions platform won't send out any email. Instead the triggering service will send out the email based on the function response.
```

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/chat-post-survey.md
> +* If there is any error during an invocation, the email won't be sent, there is no retry mechanism in the chat server for this integration.
```suggestion
* If there is any error during an invocation, the email won't be sent, there is **no retry** mechanism in the chat server for this integration.
```

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/conversation-builder.md
> +You must have an user account for the Conversational Cloud and Conversation Builder platforms. If you don't, your team should have an administrator who can create one for you.
```suggestion
You must have a user account for the Conversational Cloud and Conversation Builder platforms. If that's not the case reach out to your account manager in order to create one.
```

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/conversation-builder.md
> +{: .important}
```suggestion

```

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/conversation-builder.md
> +{: .important}
Just have the text here, no need for a box. Given that we only have that box in that chapter

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/conversational-commands.md
> +With Conversational Commands, agents are able to invoke functions from the Agent Workspace by typing `/` into the messaging input in the connections panel. This empowers agents to use a bank of preco
@eplazaso get Martin to check this specific part. As he is the daddy of the integration

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/conversational-commands.md
> +{: .important}
No need for {: .important} or notic, if it is the only thing in the chapter.
```suggestion
```

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/overview.md
> +LivePerson Functions can be connected to Conversational Cloud events at the creation time or integrated with conversational bots. Once those functions are deployed, they will be executed whenever the
```suggestion
LivePerson Functions may be listening to Conversation Cloud events or are directly linked to conversational bots. Functions will start reacting to events once they are deployed. Prior to that they are not taking any effect. 
```

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/overview.md
> +Each event has a specific input (payload) associated with it, that the triggering system will provide at runtime. When using the Invoke screen, this payload is shown on the left-hand side. During dev
```suggestion
Each event has a specific input (payload) associated with it, that the triggering system will provide at runtime. Further we provide a sample payload specific to the event, which will be displayed during the development or in the invocation screen.
```

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/overview.md
> +Each event has a specific input (payload) associated with it, that the triggering system will provide at runtime. When using the Invoke screen, this payload is shown on the left-hand side. During dev
Also move it above the notice. Directly under the other text

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/overview.md
> +Functions can be integrated with other LivePerson systems through events leveraging additional/custom functionalities that can be coded in a function.
```suggestion
Functions can be integrated with other LivePerson systems through events enabling the tailoring of the conversation cloud to your brand's needs. Creating flows and functionality that are not available out of the box.
```

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/overview.md
> + Automatic Messages (also known as System Messages) allows brands to send custom messages during conversations at Conversational Cloud Events (E.g Conversation started, Agent joined conversation, etc
```suggestion
 Automatic Messages (also known as System Messages) allow brands to send custom messages during conversations at Conversational Cloud Events (E.g Conversation started, Agent joined conversation, etc.). When any of these events are triggered during a conversation, a function can be invoked if there is a deployed function associated with that Event. If you want to learn more head over [here](liveperson-functions-event-sources-automatic-messages.html).
```

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/overview.md
> +|Conversational Command|Use this event to implement a Conversational Command that can be invoked from within the Agent Workspace in Conversational Cloud by typing "/".|Agent Workspace (NAW only)|30|
Write NAW out.
```suggestion
|Conversational Command|Use this event to implement a Conversational Command that can be invoked from within the Agent Workspace in Conversational Cloud by typing "/".|Agent Workspace (NAW only)|30|
```

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/overview.md
> +|Third-Party Bots Error Hook|Triggered when a bot, which is using the Third-Party Bots' Error Hooks is having an issue.|Bot Connector|15|
Let someone from third-party check their part. Never hurts

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/overview.md
> +|Conversational Command|Use this event to implement a Conversational Command that can be invoked from within the Agent Workspace in Conversational Cloud by typing "/".|Agent Workspace (NAW only)|30|
Should be checked by martin as well.

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/post-conversation-survey.md
> +{: .important}
Not needed
```suggestion
```

2022-03-07 09:43 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/third-party-bots.md
> +There are two types of LivePerson Functions integrations supported by Third Party Bots: **Custom integration** and **Hooks integration**. Please follow the Third Party Bots [Getting Started guide](th
Let that check by 3rd party boys. Making sure we covered all details and they should especially look out for any missing information on potential edge-cases

2022-03-07 09:59 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/post-conversation-survey.md
> +<img src="img/functions/functions_survey_bot_flow.png" alt="Functions: Post Conversation Survey Flow" style="width:100%;"/>
fixed

2022-03-07 10:21 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +To set the message empty just pass `[]` as text.
i have reomved

2022-03-07 10:21 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/automatic-messages.md
> +If no message is set in the result of the function (which it returns to the trigger, for example: `callback();` ), the default automatic message for the account will be triggered.
done

2022-03-07 10:23 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/overview.md
> +|Conversational Command|Use this event to implement a Conversational Command that can be invoked from within the Agent Workspace in Conversational Cloud by typing "/".|Agent Workspace (NAW only)|30|
I removed

2022-03-08 07:31 UTC, MSchabel approved these changes
@eplazaso @Templum Added some minor suggestions on phrasing, the content is correct. 👍

2022-03-08 07:31 UTC, MSchabel commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/conversational-commands.md
> +With Conversational Commands, agents are able to invoke functions from the Agent Workspace by typing `/` into the messaging input in the connections panel. This empowers agents to use a bank of preco
This sounds like this would work out of the box. I would start  something like:
```suggestion
When properly set up, agents can use Conversational Commands to invoke functions from the Agent Workspace. By typing `/` into the messaging input in the connections panel, all available commands are shown. This empowers agents to use a bank of preconfigured, account-specific commands, to enrich the conversation with integrated functions that will help them interact efficiently with the consumer.
```

2022-03-08 07:31 UTC, MSchabel commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/conversational-commands.md
> +It is required that your account has the New Agent Workspace enabled; please contact your account team in order to do this.
Maybe move this down under the `### Configuration`heading.

2022-03-08 07:31 UTC, MSchabel commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/conversational-commands.md
> +Agent permissions required: **Use enhanced Agent Workspace** and **FaaS-Invocation** permissions have to be enabled.
```suggestion
To be able to use Conversational Commands an Agent needs the following permissions:
* **Use enhanced Agent Workspace** 
* **FaaS-Invocation**
```
Can we maybe also add a link to how to adjust user permissions?

2022-03-08 07:31 UTC, MSchabel commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/conversational-commands.md
> +As mentioned above, the function must return either a string or a number. This response will be displayed in the Agent Workspace as a message. If the function returns anything else, the Agent will on
```suggestion
The function must return either a string or a number. This response will be displayed in the Agent Workspace as a message. If the function returns anything else, the Agent will only be shown a generic success message. If the function returns an `Error`, this will be presented to the Agent as an error message.
```

2022-03-08 08:17 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/conversational-commands.md
> +Agent permissions required: **Use enhanced Agent Workspace** and **FaaS-Invocation** permissions have to be enabled.
not sure if there is that info in developers docs (can 't find it) since this is normally done by an admistratior

2022-03-08 08:35 UTC, GFdiablo117 commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/third-party-bots.md
> +<tr><td>com.liveperson.bot-connectors-worker.error.aivendor.faas.failed-faas-request</td><td>This indicates an issue during Faas invocation.</td></tr>
```suggestion
<tr><td>com.liveperson.bot-connectors-worker.error.aivendor.faas.failed-bot-action</td><td>This indicates an issue during the invocation of an additional Liveperson Function.</td></tr>
<tr><td>com.liveperson.bot-connectors-worker.error.aivendor.faas.testConnection</td><td>>This happens when the Liveperson Function is not responding in time or with a bad status .</td></tr>
<tr><td>com.liveperson.bot-connectors-worker.error.aivendor.faas.parse-message.malformed-alternative-intents</td><td>>This indicates a wrong parsing of alternative intents inside the Liveperson Function .</td></tr>
```

2022-03-08 08:35 UTC, GFdiablo117 commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/third-party-bots.md
> +<tr><td>com.liveperson.bot-connectors-worker.error.aivendor.faas.failed-faas-request</td><td>This indicates an issue during Faas invocation.</td></tr>
Don't know if we go for Faas or Liveperson Function. Please check and align

2022-03-08 08:40 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/third-party-bots.md
> +<tr><td>com.liveperson.bot-connectors-worker.error.aivendor.faas.failed-faas-request</td><td>This indicates an issue during Faas invocation.</td></tr>
Liveperson Function is it

2022-03-08 09:17 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/conversational-commands.md
> +It is required that your account has the New Agent Workspace enabled; please contact your account team in order to do this.
good idea,

2022-03-08 13:15 UTC, Templum approved these changes
LGTM

2022-03-10 15:43 UTC, chrbrt approved these changes

2022-03-10 15:43 UTC, chrbrt commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/post-conversation-survey.md
> +Create a new function using one of the messaging survey templates. There are are the following events:
```suggestion
Create a new function using one of the messaging survey templates. There are the following events:
```

2022-03-10 15:43 UTC, chrbrt commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/post-conversation-survey.md
> +Currently, only one function per event type can be created. If there are multiple types of functionality needed that stem from the same event invocation, these should be coded into the same function.
```suggestion
Currently, you can only create one function of this event type. If there are multiple types of functionality needed that require the same event, than this must be handled by a single function's code.
```

2022-03-10 15:43 UTC, chrbrt commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/third-party-bots.md
> +**Third-Party Bots Post Hook**: Triggered when a bot, which is using the Third-Party Bots' Post Hooks receives a message. The function will be invoked after the vendor responded. The function gets in
```suggestion
**Third-Party Bots Post Hook**: Triggered when a bot, which is using the Third-Party Bots' Post Hooks receives a message. The function will be invoked after the vendor responded. The function gets invoked on every message the customer sends. It enables you to modify or expand the response of the payload.
```

2022-03-11 09:59 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/overview.md
> +The amount of functions connected to a specific event is restricted and can be seen in the table below.
I moved to the top

2022-03-11 10:23 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/EventSources/overview.md
> +Conversation Builder Bots can be integrated with Functions. If there is some custom logic that can be done with a function, you can do it with Conversation Builder.
changed to this: _Conversation Builder Bots can be integrated with Functions. If there is some custom logic that is not supported by CB platform, this can be done with a function._

2022-03-21 12:42 UTC, merged