FC-1145: :memo:  Foundations Chapter
Templum/developers-community pull request #8
Opened 2022-03-10 12:16 UTC by Templum

2022-03-11 15:19 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/concepts.md
> +<img class="fancyimage" alt="Functions: Event Invocation" src="img/functions/functions_concept_event_invocation.png">
I saw that the images have a transparent background with is good but when the documentation is in Dark mode the font of the schemas won't be changed and won't be visible...

2022-03-11 15:22 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/concepts.md
> +<img class="fancyimage" alt="Functions: Event Invocation" src="img/functions/functions_concept_event_invocation.png">
also in: "built response from received responses" -> "buil**d** response...."

2022-03-11 15:55 UTC, eplazaso requested changes

2022-03-11 15:55 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/best-practices.md
> +Most of our API's are based around Promises and therefore can be easily consumed in an `Async-Await` fashion. Leveraging [Async-Await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Referenc
```suggestion
Most of our API's are based around Promises and therefore can be easily consumed in an `Async-Await` fashion. Leveraging [Async-Await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await) over [Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises)/Callbacks eases the error handling by allowing `try-catch` blocks. Further when leveraging Promise-Chains users of our platform tend to forget the `.catch` statement and only handle the happy path with `.then`. Resulting in unhandled promise rejections, without any logging insights, which usually manifests as a timeout error (as the callback never gets called). Additionally, it keeps the code shallow, avoiding deep nesting. This benefits the overall maintainability of functions.
```

2022-03-11 15:55 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/best-practices.md
> +Our [Secret store](liveperson-functions-foundations-features.html#secret-store) allows functions to fetch credentials in a secure way and also modify them if needed. So in productive use we strongly
```suggestion
Our [Secret store](liveperson-functions-foundations-features.html#secret-store) allows functions to fetch credentials in a secure way and also modify them if needed. So in productive use we strongly encourage caching the secret, loading it once, and then reusing it throughout the Lifecycle of a Function instance. Please see the below coding for an example setup, which leverages local variables to achieve this. Please be aware that this is only possible if the secrets are not getting modified and therefore are more or less static. For things like tokens, you can adjust the caching to reuse the token while it is still valid and not yet expired.
```

2022-03-11 15:55 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/best-practices.md
> +Not related to secret caching, but to usage of secret store itself. Please only put secrets and credentials in it, things like URL's or other configuration parameter are better placed in environment
```suggestion
Not related to secret caching, but to the usage of the secret store itself. Please only put secrets and credentials in it, things like URLs or other configuration parameters are better placed in environment variables.
```

2022-03-11 15:55 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/best-practices.md
> +> The above coding will check if the value already exists in the `secretCache` and if that's not the case will read it from the secret store. As the comment highlights it is important that `secretCac
```suggestion
> The above coding will check if the value already exists in the `secretCache` and if that's not the case will read it from the secret store. As the comment highlights, it is important that `secretCache` is outside of any function-scope in order to ensure it does not get cleaned up.
```

2022-03-11 15:55 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/best-practices.md
> +We strongly recommend the usage of Environment Variables to make functions easier to configure, even for none technically people. Given they don't need to understand the code, but only adjust environ
```suggestion
We strongly recommend the usage of Environment Variables to make functions easier to configure, even for none technically people. Given they don't need to understand the code, but only adjust environment variables if needed. This also allows you to make the code cleaner by moving the configuration part into environment variables. If you want to learn more about the Environment Variables setup head over [here](liveperson-functions-getting-started-configure.html#environment-variables).
```

2022-03-11 15:55 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/best-practices.md
> +Environment Variable changes need to be deployed in order to take affect. And Environment Variables are always string, meaning you need to parse any none string type prior to using it
```suggestion
Environment Variables changes need to be deployed in order to take effect. And Environment Variables are always a string, meaning you need to parse any none string type prior to using it
```

2022-03-11 15:55 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/best-practices.md
> +As documented in our [Event Source Page](liveperson-functions-event-sources-overview.html) some of the Event Sources will actively react to error's raised by your function. And reinvoke your function
```suggestion
As documented in our [Event Source Page](liveperson-functions-event-sources-overview.html) some of the Event Sources will actively react to errors raised by your function. And reinvoke your function with the same event/payload following at least one approach. Usually, functions will be triggered only once, but they can also be invoked multiple times. Therefore you should design your function in such a way that a retry won't have negative side effects or cause unexpected behavior on your side.
```

2022-03-14 10:58 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/concepts.md
> +<img class="fancyimage" alt="Functions: Event Invocation" src="img/functions/functions_concept_event_invocation.png">
Done [a729ade](https://github.com/Templum/developers-community/pull/8/commits/a729ade47ce8b87d681fcf87247ae92935be008c)

2022-03-14 15:48 UTC, eplazaso requested changes
Still have more files to review

2022-03-14 15:48 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/external-invocation.md
> +`FaaSDetailedExceptions` occur when the request has been rejected by the service. For instance if the UUID of the lambda for invocation request does not exist.
```suggestion
`FaaSDetailedExceptions` occur when the request has been rejected by the service. For instance, if the UUID of the lambda for invocation request does not exist.
```

2022-03-14 15:48 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/external-invocation.md
> +In order to get more details we recommend using the `getFaaSError`-method. A detailed list of possible errors can be found [here](liveperson-functions-foundations-error-codes.html). `FaaSLambdaExcept
```suggestion
In order to get more details, we recommend using the `getFaaSError`-method. A detailed list of possible errors can be found [here](liveperson-functions-foundations-error-codes.html). `FaaSLambdaException` inherits from `FaaSDetailedException`. It is only raised during invocations if the error is caused by the implementation of the function itself.
```

2022-03-14 15:48 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/external-invocation.md
> +The default Authentication method is OAuth 2.0 with grant type `client_credentials`. Please check the [above chapter](#authorization-process) on the necessary steps
```suggestion
The default Authentication method is OAuth 2.0 with grant type `client_credentials`. Please check the [above chapter](#authorization-process) on the necessary steps.
```

2022-03-14 15:48 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/external-invocation.md
> +* `isImplemented` this method allows to check if an event or a specific uuid is implemented. It is a best practice to check this prior to invoking
we should check if is correct " allows to check " (for me sounds good but is not clear, maybe some native English speaker can help) or is "allows checking"

2022-03-14 15:48 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/external-invocation.md
> +* `getLambdas` this method will return all functions and there states that belong to specified account
```suggestion
* `getLambdas` this method will return all functions and their states that belong to a specified account
```

2022-03-14 15:48 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/external-invocation.md
> +A more detailed version of the documentation can be found inside our [github repository](https://github.com/LivePersonInc/faas-client-node). If you experience an issue or have a wish, please create a
Think should be GitHub instead of github, also Grammarly says that

2022-03-14 15:48 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/features.md
> +Some usecases require a scheduled invocation of a function. Two example for this would be OAuth 2.0 related refresh operations or scheduled invocation to keep [functions warm](liveperson-functions-fo
```suggestion
Some usecases require a scheduled invocation of a function. Two examples for this would be OAuth 2.0 related refresh operations or scheduled invocation to keep [functions warm](liveperson-functions-foundations-concepts.html#cold-start). We allow the scheduling of functions based on CRON expressions, we suggest to leverage [this page](https://crontab.guru/) to verify your expression. Please be aware of the following limitation:
```

2022-03-14 15:48 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/features.md
> +To create a Schedule you will need to hit the "Create a schedule"-Button, than you can choose your productive functions from the drop down. After that provide a valid cron expression. The UI will alw
```suggestion
To create a Schedule you will need to hit the "Create a schedule"-Button, then you can choose your productive functions from the drop down. After that provide a valid cron expression. The UI will always calculate the next invocation in your **local** time and display it to you. In case you used an invalid expression the UI will provide you with valid example values. Further, you may adjust the displayed payload. It will be then used for the scheduled invocation and therefore is available to the function during the invocation.
```

2022-03-14 15:48 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/features.md
> +* LP Client: Eases the interactions with common LivePerson Api's
```suggestion
* LP Client: Eases the interactions with common LivePerson APIs
```

2022-03-14 15:48 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/features.md
> +During the [provisioning](liveperson-functions-provisioning.html) process of the account a couple of default secrets are created. Those are not displayed by default, but they are viewable.
```suggestion
During the [provisioning](liveperson-functions-provisioning.html) process of the account, a couple of default secrets are created. Those are not displayed by default, but they are viewable.
```

2022-03-14 15:48 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/features.md
> +As explained within our [networking foundation](liveperson-functions-foundations-networking.html) the communication between a function and external services is subject to a domain allow list, also ca
```suggestion
As explained within our [networking foundation](liveperson-functions-foundations-networking.html), the communication between a function and external services is subject to a domain allow list, also called whitelist. The next paragraphs should highlight how to add new domains to the whitelist and also how to remove them. Further, it will provide some important hints based on frequent questions received surrounding the whitelisting of domains.
```

2022-03-14 15:48 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/deep-dive-ui.md
> +The domain is added by inserting it and than clicking the "Add"-Button next to the input field. Once it is saved it will be reflected in the domain list below.
```suggestion
The domain is added by inserting it and then clicking the "Add"-Button next to the input field. Once it is saved it will be reflected in the domain list below.
```

2022-03-15 10:58 UTC, eplazaso requested changes

2022-03-15 10:58 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/limitations.md
> +This page will offer you with a high level overview about all limitations that are in place. This should help you determine if your use-case is feasible and you want to move forward with the LivePers
```suggestion
This page will offer you a high level overview of all limitations that are in place. This should help you determine if your use-case is feasible and you want to move forward with the LivePerson Functions platform.
```

2022-03-15 10:58 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/limitations.md
> +* Domain name needs to be valid based on [RFC1035](https://datatracker.ietf.org/doc/html/rfc1035)
```suggestion
* Domain names need to be valid based on [RFC1035](https://datatracker.ietf.org/doc/html/rfc1035)
```

2022-03-15 10:58 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/limitations.md
> +This is not a direct limitation, but a strong discouragement from our side. Please avoid the usage of `setTimeout` in your code. Given that a single function instance me handle more than one request,
```suggestion
This is not a direct limitation, but a strong discouragement from our side. Please avoid the usage of `setTimeout` in your code. Given that a single function instance may handle more than one request, having timeouts running may negatively impact performance. Especially when the function is experiencing high traffic volumes. Generally, any coding that blocks or fills up the event loop is something that should be avoided. If that is a deal breaker for you, we advise you to look into an alternative solution.
```

2022-03-15 10:58 UTC, eplazaso commented on pages/Documents/Reporting/OutboundReportingAPI/overview.md
> +**2. Campaign - Get analytics for the given campaign**
What is this? this is not FAAs, maybe was due to merge?

2022-03-15 10:58 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/networking.md
> +In this chapter we want to explain the existing networking constraints and the overall process which allows functions to communicate to the outside world. It is important to highlight from the start
```suggestion
In this chapter, we want to explain the existing networking constraints and the overall process which allows functions to communicate to the outside world. It is important to highlight from the start that we limit the communication means available to functions. It is not possible for functions to use any other protocol than HTTP or HTTPS, that means for example that sending emails from a function would be only possible if you leverage web-based service.
```

2022-03-15 10:58 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/networking.md
> +Further the communication from the function to external services is bound to checks. This means you may not use external services that are not defined in your account specific allowed domain list ([w
```suggestion
Further, the communication from the function to external services is bound to checks. This means you may not use external services that are not defined in your account specific allowed domain list ([whitelist](liveperson-functions-foundations-features.html#domain-whitelisting)). Those checks are performed by the service that handles the outbound communication for the functions. The communication to external services runs over HTTP tunneling (via [CONNECT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT)). This flow is shown in the graphic below.
```

2022-03-15 10:58 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/networking.md
> +As shown the function will reach out to the proxy using the `CONNECT`-method while specifying a target. If the target domains is not on the allowed domain list it refuses the connection and aborts th
```suggestion
As shown the function will reach out to the proxy using the `CONNECT`-method while specifying a target. If the target domain is not on the allowed domain list it refuses the connection and aborts the request. If it is included it will reach out the target and establish a TCP connection. Once that is succeeded it will return a successful response to the function and hand-over the TCP connection to the target by tunneling. The further SSL handshake is then performed between the function and the target directly. Therefore the proxy is not able to listen to the ongoing communication between function and target, this implies from the point the TCP handshake happened we don't have any insights.
```

2022-03-15 10:58 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/ToolbeltDocumentation/faas-context-service-client.md
> +Returns the specified session containing all of it's properties.
```suggestion
Returns the specified session containing all of its properties.
```

2022-03-15 10:58 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/ToolbeltDocumentation/faas-context-service-client.md
> +Returns a list containing all session in the specified namespaces.
```suggestion
Returns a list containing all sessions in the specified namespaces.
```

2022-03-15 14:47 UTC, chrbrt requested changes

2022-03-15 14:47 UTC, chrbrt commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/networking.md
> +Further the communication from the function to external services is bound to checks. This means you may not use external services that are not defined in your account specific allowed domain list ([w
```suggestion
Additionally, the communication from the function to external services is bound to checks. This means you may not use external services that are not defined in your account specific allowed domain list ([whitelist](liveperson-functions-foundations-features.html#domain-whitelisting)). Those checks are performed by the service that handles the outbound communication for the functions. The communication to external services runs over http tunneling (via [CONNECT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT)). This flow is shown in the graphic below.
```

2022-03-15 14:47 UTC, chrbrt commented on pages/Documents/DeveloperTools/LivePersonFunctions/ToolbeltDocumentation/faas-context-service-client.md
> +session was provided it will fallback to default session of the namespace.
```suggestion
Get the value of the specified property on the defined session. If no
session was provided it will fallback to default session of the namespace.
```

2022-03-15 14:47 UTC, chrbrt commented on pages/Documents/DeveloperTools/LivePersonFunctions/ToolbeltDocumentation/faas-context-service-client.md
> +a property/properties already exist they will be updated.
```suggestion
If no session was provided it will fallback to the default session of the
namespace. All values will be stored in their JSON serialized version. Given
a property/properties already exist they will be updated.
```

2022-03-15 15:15 UTC, eplazaso requested changes

2022-03-16 10:33 UTC, eplazaso requested changes

2022-03-16 10:33 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/ToolbeltDocumentation/mtls-client.md
> +Set this flag to true, to automatically stringify body + set correct content header. And parse response to json.
I thin json should be with cap letters  (JSON) everywhere

2022-03-16 10:33 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/ToolbeltDocumentation/mtls-client.md
> +Time in ms until request should timeout. Please be aware that MTLS call take longer then regular http calls.
```suggestion
Time in ms until request should timeout. Please be aware that MTLS calls take longer than regular HTTP calls.
```

2022-03-16 10:33 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/ToolbeltDocumentation/mtls-client.md
> +has an self-signed certificate. The certificate needs to be in PEM format.
```suggestion
has a self-signed certificate. The certificate needs to be in PEM format.
```

2022-03-16 10:33 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/ToolbeltDocumentation/orchestrator-client.md
> +Defines the strategy to follow in case on error.
```suggestion
Defines the strategy to follow in case of error.
```

2022-03-16 10:33 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/ToolbeltDocumentation/secret-client.md
> +Will raise an SecretError if there is no secret for the provided key.
```suggestion
Will raise a SecretError if there is no secret for the provided key.
```

2022-03-16 10:33 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/ToolbeltDocumentation/secret-client.md
> +Will raise an SecretError if there is no secret with the specified key.
```suggestion
Will raise a SecretError if there is no secret with the specified key.
```

2022-03-16 10:33 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/ToolbeltDocumentation/toolbelt.md
> +Returns an MTLS Client which is configured with the provided config. Please make sure that you set allowSelfSigned
```suggestion
Returns an MTLS Client which is configured with the provided config. Please make sure that you set _allowSelfSigned_
```

2022-03-16 10:33 UTC, eplazaso commented on pages/Documents/DeveloperTools/LivePersonFunctions/ToolbeltDocumentation/toolbelt.md
> +Returns an Secret Client, which is setup to allow read and update access
```suggestion
Returns a Secret Client, which is setup to allow read and update access
```

2022-03-21 12:44 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/error-codes.md
> +| 901           |   Error during lambda execution       | Lambda Execution failed due to an issue with the lambda coding. This can include runtime exception, exceeding processing window & returning o
```suggestion
| 901           |   Error during lambda execution       | Function Execution failed due to an issue with the function coding. This can include runtime exception, exceeding processing window & returning of an error by the lambda                                                                                                                          |
```

2022-03-21 12:45 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/error-codes.md
> +| 901           |   Error during lambda execution       | Lambda Execution failed due to an issue with the lambda coding. This can include runtime exception, exceeding processing window & returning o
Within text we should stick to function, lambda in error codes or similar is fine.

2022-03-21 12:46 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/external-invocation.md
> +We support the following [grant types](https://oauth.net/2/grant-types/) out of the OAuth 2.0 specification. If you want to learn more about OAuth 2.0 check out [this video](https://www.youtube.com/w
It was already used in the existing documentation. Hence I believe it is fine. Actually will be finally on our team lead to call a shot. Will make a not for that 👍

2022-03-21 12:48 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/external-invocation.md
> +* `invokeByUUID` this method allows to invoke a productive function by it's UUID. You may leverage `isImplemented` to check if the function is productive
Wanted to stay as close as possible to the actual use. In order to avoid any potential friction here.

2022-03-21 12:55 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/ToolbeltDocumentation/mtls-client.md
> +Set this flag to true, to automatically stringify body + set correct content header. And parse response to json.
It's generated from source code. Hence we should adjust and then recreate it.

2022-03-21 13:36 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/external-invocation.md
> +We support the following [grant types](https://oauth.net/2/grant-types/) out of the OAuth 2.0 specification. If you want to learn more about OAuth 2.0 check out [this video](https://www.youtube.com/w
Spoke with him, he is fine with it

2022-03-21 13:46 UTC, eplazaso approved these changes

2022-03-21 14:09 UTC, merged